//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs464_project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovement
    {
        public int MovementId { get; set; }
        public int ProductId { get; set; }
        public string MovementType { get; set; }
        public int Quantity { get; set; }
        public string RefType { get; set; }
        public Nullable<int> RefId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Note { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
